### ISSUE TITLE
comfyui直接崩溃了

### ISSUE THREAD

**Issue by 11whitewater** [smthemex/ComfyUI_EchoMimic#11]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
comfyui直接崩溃了，无法使用gpu版本

**Comment by smthemex** [comment]
我删除了需求文件的几个库，低版本的也能用

**Comment by shengshiai** [comment]
您好，请问一下comfyui打不开了
raise AssertionError（“Torch not compiled with CUDA enabled”）
AssertionError： Torch not compiled with CUDA enabled

**Comment by smthemex** [comment]
卸载插件，安装最新的。

**Comment by 11whitewater** [comment]
我是把插件卸载了，然后运行release版本中自带的一个update and python程序（具体名字不太记得清了），就可以继续正常使用comfyui了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 凌晨0:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [smthemex/ComfyUI_EchoMimic] comfyui直接崩溃了 (Issue #11)




 
您好，请问一下comfyui打不开了
 raise AssertionError（“Torch not compiled with CUDA enabled”）
 AssertionError： Torch not compiled with CUDA enabled

**Comment by smthemex** [comment]
因为装facenet_pytorch的适合，如果你的torch版本不对，它会自动安装，但是自动安装的不带cuda，所以就崩了。
