### ISSUE TITLE
v1为什么执行这么慢？

### ISSUE THREAD

**Issue by longit123** [smthemex/ComfyUI_EchoMimic#116]
GPU：4090
系统：win10
torch：2.3.1+cu121
我安装了万能君的exe版，同一个图片和音频，3s/it，而使用comfyui，却要至少15s/it，

### 测试图片和音频
![metahuman_002](https://github.com/user-attachments/assets/8db0394d-8fda-4db0-90f1-d489c5f96495)

### 万能君版界面和执行进度
![vx_capture_211224120829](https://github.com/user-attachments/assets/ff4c0f9c-444a-44bf-bb33-9ad722c3bf6d)
![vx_capture_531224120808](https://github.com/user-attachments/assets/cbce1b5b-b638-4b84-a329-b00d526c0192)
![vx_capture_141224120823](https://github.com/user-attachments/assets/2507d367-5df0-499b-bcc1-f0521165f843)
![vx_capture_221224120823](https://github.com/user-attachments/assets/24009679-1e87-44c8-9e41-430824f3a12d)
![vx_capture_571224120825](https://github.com/user-attachments/assets/36dc13f2-0e59-49ee-ad7f-c266465964af)

### comfyui界面和执行进度
![vx_capture_361224120813](https://github.com/user-attachments/assets/6ca7186a-0c41-48fa-b26a-a6401465a092)

![vx_capture_301224120814](https://github.com/user-attachments/assets/6b155c3a-b5e4-4a40-af57-6bbfc2da91f4)

**Comment by smthemex** [comment]
我看你截图是用的不同图幅，请换成同一图幅处理

**Comment by smthemex** [comment]
我说的是输出图片的图幅，comfyUI会按输出图片的尺寸自动缩放的，一样的图片，你输出是成768，就按768处理的。处理768和512能一样吗？
