### ISSUE TITLE
是否有计划支持高版本torch及cuda12.4

### ISSUE THREAD

**Issue by ArvinC** [smthemex/ComfyUI_EchoMimic#13]
我的cuda版本比较高，安装低版本torch会报错，一直无法安装成功，后续是否有计划支持高版本

**Comment by westNeighbor** [comment]
cuda 12.4没问题，torch 2.2.0 work

**Comment by smthemex** [comment]
facenet_pytorch 目前仅支持最高torch 2.2.0，这个暂时没有更好的解决办法

**Comment by Hoerwozi** [comment]
大佬你打错字了，应该是cu118版本吧，你打成181了

**Comment by smthemex** [comment]
是的 打错字了

**Comment by Rachellaw888** [comment]
我是 torch2.2.2+121,   忙活了一天，结果却晕死了： 
“Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic module for custom nodes: No module named 'facenet_pytorch'”   
哎，无语、无奈啊。。。。不想改 torch  好大工程啊。。。哭死，除了放弃还能怎么办？？？？？？？

**Comment by smthemex** [comment]
torch有什么大工程的，卸载了再装就是了。
