### ISSUE TITLE
AttributeError: module 'ffmpeg' has no attribute 'Error'

### ISSUE THREAD

**Issue by laidingq** [smthemex/ComfyUI_EchoMimic#2]

**Comment by smthemex** [comment]
Can you provide detailed information about the error?

**Comment by laidingq** [comment]
got prompt
loaded temporal unet's pretrained weights from D:\ComfyUI\models\echo_mimic\unet ...
Load motion module params from D:\ComfyUI\models\echo_mimic\motion_module.pth
Loaded 453.20928M-parameter motion module
!!! Exception during processing!!! module 'ffmpeg' has no attribute 'Error'
Traceback (most recent call last):
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 427, in em_main
    output_video = process_video(image, audio, width, height, length, seeds, facemask_ratio,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 148, in process_video
    video = pipe(
            ^^^^^
  File "D:\ComfyUI\miniconda\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\pipelines\pipeline_echo_mimic.py", line 395, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 46, in load_audio
    except ffmpeg.Error as e:
           ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'Error'

**Comment by smthemex** [comment]
ffmpeg needs to be added to the system's environment variables. The following is the official website's guidance：
Download ffmpeg-static
Download and decompress [ffmpeg-static](https://www.johnvansickle.com/ffmpeg/old-releases/ffmpeg-4.4-amd64-static.tar.xz), then
export FFMPEG_PATH=/path/to/ffmpeg-4.4-amd64-static

**Comment by laidingq** [comment]
![屏幕截图 2024-07-14 143020](https://github.com/user-attachments/assets/0e43d2b9-0f9f-4343-8169-d68ddc220ee6)
这样对吗

**Comment by smthemex** [comment]
官方的方法是Linux的，你的地址后面加个xxx\bin ,bin这个文件是有3个exe文件 的。 添加后，控制台输入ffmpeg -version
查看是否添加成功

**Comment by laidingq** [comment]
这个下载下来解压没有bin文件夹

**Comment by only1xiaobai** [comment]
> 这个下载下来解压没有bin文件夹

你直接去谷歌搜FFMPEG，会有官网，下载后，然后按照刚才说的，加到环境变量里

**Comment by laidingq** [comment]
![image](https://github.com/user-attachments/assets/e48aa9be-e34b-4be5-b942-3cbe96556352)
我本来有6.0的 其他插件是可以用的

**Comment by only1xiaobai** [comment]
> ffmpeg -version

那个4.4版本下载了部署到环境变量里没用。。。得换个
我也在找，我也遇到这个问题了

**Comment by smthemex** [comment]
我检查一下代码里的ffmpeg的路径查找问题，可以试着直接在系统环境变量里，新建FFMPEG_PATH ，路径设置为你的路径path/ffmpeg版本/bin

**Comment by ioritree** [comment]
官方的我可以用,但是你的插件卻有ffmpeg問題

**Comment by smthemex** [comment]
我看了下你的报错问题，ffmpeg其实是导入成功了，但是缺少input函数，也就是说，是ffmpeg的问题，我找了下方法，请按以下操作，ffmpeg是没有input的。
pip uninstall ffmpeg
pip install ffmpeg-python

**Comment by laidingq** [comment]
已经解决，谢谢大佬

**Comment by JimWang151** [comment]
> 已经解决，谢谢大佬

兄弟，你最后是怎么解决的？我也遇到这样的问题。

多谢指导。

**Comment by laidingq** [comment]
pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python

> > 已经解决，谢谢大佬
> 
> 兄弟，你最后是怎么解决的？我也遇到了这样的问题。
> 
> 非常感谢指导。

**Comment by JimWang151** [comment]
> pip uninstall ffmpeg pip uninstall ffmpeg-python pip install ffmpeg-python
> 
> > > 已经解决，谢谢大佬
> > 
> > 
> > 兄弟，你最后是怎么解决的？我也遇到了这样的问题。
> > 非常感谢指导。

多谢兄弟，不过我的问题比较复杂，主要解决过程是这样：
第一个问题：xformers版本和pytorch冲突，后来针对pytorch 2.2装的xformers
第二：ffmepg的环境变量，分两步，1：在官网下载win版的ffmpeg后，在环境变量中path加了ffmpeg的bin目录  2：在环境变量中添加FFMPEG_HOME
第三：uninstall ffmpeg和ffmpeg-python 然后reinstall ffmpeg-python
过程中，还重新安装了cuda pytorch 1.22以及相应的torchvision,torchtext,torchaudio等。

特别写下来，给其他兄弟也参考一下。

没想到你回复这么快，多谢哈。
