### ISSUE TITLE
'AudioData' object is not subscriptable

### ISSUE THREAD

**Issue by huibing99** [smthemex/ComfyUI_EchoMimic#22]
Error occurred when executing Echo_Sampler:

'AudioData' object is not subscriptable

File "/data/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/data/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/data/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/data/ComfyUI/custom_nodes/ComfyUI_EchoMimic/EchoMimic_node.py", line 564, in em_main
torchaudio.save(audio_file, audio["waveform"].squeeze(0), sample_rate=audio["sample_rate"])

我判断是应该是导入音频的ComfyUI-AudioScheduler节点的audio没有waveform的字段。
我改动了这行代码：
更改前
torchaudio.save(audio_file, audio["waveform"].squeeze(0), sample_rate=audio["sample_rate"])
更改后：
torchaudio.save(audio_file, torch.tensor(audio.audio_data).unsqueeze(0), sample_rate=audio.sample_rate)

也无法运行，请问该如何解决？

**Comment by smthemex** [comment]
你的音频格式是什么？comfyUI默认的torchaudio用的是soundfile模块，按理是内置了的，你该的那段代码没有匹配上comfyUI音频节点的输出格式，他就是做了个字典"waveform" 和"sample_rate"的字典。

**Comment by huibing99** [comment]
> 你的音频格式是什么？comfyUI默认的torchaudio用的是soundfile模块，按理是内置了的，你该的那段代码没有匹配上comfyUI音频节点的输出格式，他就是做了个字典"waveform" 和"sample_rate"的字典。

我使用了example中的wav音频文件，mp3也试过，同样的报错。

**Comment by smthemex** [comment]
你看看comfyUI的audio节点，搞不好是audio节点有变动

**Comment by DoItEric** [comment]
我想我找到这个节点了，名字叫：ComfyUI-speech-dataset-toolkit  似乎需要一系列日语语言包，我并无法安装成功，如果有人能安装成功记得叫我一下

**Comment by Hoerwozi** [comment]
这个问题最后是怎么解决的，我遇到了一个相似的问题，也说是waveform的格式问题。
2024-07-23 02:25:22,785-40-INFO-/home/gpu/src/ComfyUI/execution.py:154: Node 14 class_type Echo_Sampler took 30.282338619232178 seconds to execute
2024-07-23 02:25:23,524-40-ERROR-/home/gpu/src/ComfyUI/execution.py:182: !!! Exception during processing!!! string indices must be integers
2024-07-23 02:25:23,526-40-ERROR-/home/gpu/src/ComfyUI/execution.py:183: Traceback (most recent call last):
  File "/home/gpu/src/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/gpu/src/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/gpu/src/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/gpu/src/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py", line 523, in combine_video
    channels = audio['waveform'].size(1)
TypeError: string indices must be integers

**Comment by Hoerwozi** [comment]
> 这个问题最后是怎么解决的，我遇到了一个相似的问题，也说是waveform的格式问题。 2024-07-23 02：25：22,785-40-INFO-/home/gpu/src/ComfyUI/execution.py：154：节点 14 class_type Echo_Sampler执行 30.282338619232178 秒 2024-07-23 02：25：23,524-40-ERROR-/home/gpu/src/ComfyUI/execution.py：182：!!处理过程中出现异常!!字符串索引必须是整数 2024-07-23 02：25：23,526-40-ERROR-/home/gpu/src/ComfyUI/execution.py：183：回溯（最近一次调用）：文件“/home/gpu/src/ComfyUI/execution.py”，第 153 行，在 recursive_execute output_data中，output_ui = get_output_data（obj，input_data_all） 文件“/home/gpu/src/ComfyUI/execution.py”，第 82 行，在get_output_data return_values = map_node_over_list（obj， input_data_all，obj。FUNCTION， allow_interrupt=True） 文件 “/home/gpu/src/ComfyUI/execution.py”，第 75 行，在 map_node_over_list results.append（getattr（obj， func）（**slice_dict（input_data_all， i））） 文件“/home/gpu/src/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/nodes.py”，第 523 行，在 combine_video 通道中 = audio['waveform'].size（1） TypeError：字符串索引必须是整数

没事了VHS更新一下就好了

**Comment by guoyin90** [comment]
> > 你的音频格式是什么？comfyUI默认的torchaudio用的是soundfile模块，按理是内置了的，你该的那段代码没有匹配上comfyUI音频节点的输出格式，他就是做了个字典"waveform" 和"sample_rate"的字典。
> 
> 我使用了example中的wav音频文件，mp3也试过，同样的报错。

换成VHS里面的Load Audio (Upload)节点就可以了

**Comment by smthemex** [comment]
> > > 你的音频格式是什么？comfyUI默认的torchaudio用的是soundfile模块，按理是内置了的，你该的那段代码没有匹配上comfyUI音频节点的输出格式，他就是做了个字典"waveform" 和"sample_rate"的字典。
> > 
> > 
> > 我使用了example中的wav音频文件，mp3也试过，同样的报错。
> 
> 换成VHS里面的Load Audio (Upload)节点就可以了

新方法不需要Load Audio (Upload) 直接用，但是需要新版的VH
