### ISSUE TITLE
求问 ValueError: DownEncoderBlock2D does not exist 提示这个是什么原因 

### ISSUE THREAD

**Issue by longzy1** [smthemex/ComfyUI_EchoMimic#24]
所有模型都按目录放置了
怕目录不对 VAE我还复制了三份 放了好几个位置
这个提示 查出来是 diffusers的版本不对 试了0.26和0.29都不行呢
求解

![image](https://github.com/user-attachments/assets/97ef6a45-8d12-4826-9e15-9628b329cf89)

![image](https://github.com/user-attachments/assets/244a2122-b436-457b-b6c7-36f7d0006282)

**Comment by TwhiteShark** [comment]
我也遇到了这问题，求解

**Comment by smthemex** [comment]
检查删掉unet的config文件，检查unet的模型文件是否正确

**Comment by TwhiteShark** [comment]
@smthemex 有效，我检查并重新下载了config文件。
