### ISSUE TITLE
The video preview output from the example workflow does not contain any audio data.

### ISSUE THREAD

**Issue by hndrr** [smthemex/ComfyUI_EchoMimic#28]
The currently published workflow example does not include audio in the output preview video.
Currently, I have the output by replacing `VHS_VideoCombine` with `CombineVideo` and connecting it as shown in the image.
This is because the output audio types do not match.

This is a little difficult to use and we would be very happy if you could improve the audio output. 
Or if there is a better way, please let me know.

![2024-07-20 222122](https://github.com/user-attachments/assets/27f8ada6-a93f-44ed-a553-1354e1347a30)

**Comment by hndrr** [comment]
I tried again,
When using `VHS_VideoCombine` , it was necessary to relay the input audio file across the `VHS_Load Audio (Path)` like this.
I hope this helps someone else who is having the same problem.

![2024-07-21 095827](https://github.com/user-attachments/assets/f1f5e50d-5178-4d4d-8121-1d0e51017809)

**Comment by smthemex** [comment]
The VH node has currently changed the input format of the audio to standard comfyUI audio. Regarding the issue you mentioned, I will make the necessary changes in the next update

**Comment by hndrr** [comment]
Thank you. I will bring you the next update.
I was not even aware that the vh node had been updated.
