### ISSUE TITLE
求问：Error occurred when executing Echo_LoadModel: stabilityai/sd-vae-ft-mse does not appear to have a file named config.json

### ISSUE THREAD

**Issue by bayun2016** [smthemex/ComfyUI_EchoMimic#29]
Error occurred when executing Echo_LoadModel:
stabilityai/sd-vae-ft-mse does not appear to have a file named config.json.
![image](https://github.com/user-attachments/assets/61a0d9ee-f739-4f7d-92d6-7d7c0732ca00)
但是已经反复确认了，对应目录里有config.json这个文件：
![image](https://github.com/user-attachments/assets/b58cce64-2393-4e34-9b7a-5d0200bfde7c)

**Comment by smthemex** [comment]
你删掉config重新下载一个试试，自定义vae路径我一直没有测试过，回头我测试一下。路径地址记得用/，

**Comment by bayun2016** [comment]
> 你删掉config重新下载一个试试，自定义vae路径我一直没有测试过，回头我测试一下。路径地址记得用/，

感谢，看了您之前一个closed的回复，把vae路径改成绝对路径后正常运行了
