### ISSUE TITLE
STOP MAKING NODES THAT BREAK COMFY INSTALLS!!!!!!!!!!!

### ISSUE THREAD

**Issue by inferno46n2** [smthemex/ComfyUI_EchoMimic#33]
....if you don't know how to make a  reqs file that doesn't overwrite torch and other dependences critical to Comfy install.. DONT MAKE A GOD DAMN NODE

The amount of people you are bricking their comfy installs on windows is astronomical... 

Literally all you need to do is add --no-deps after facenet_pytorch in your reqs file... problem solved..... but nope?

**Comment by inferno46n2** [comment]
> Facenet_pytorch is a necessary dependency, and even if I don't include it, the person who installs this node won't be able to use it. Thank you for your suggestion, but for any node that needs to be installed, please read the readme.

I told you how to fix it but you ignored me

**Comment by smthemex** [comment]
Okay, I deleted OpenCV Python from the requirements. txt file, you win
