### ISSUE TITLE
stabilityai/sd-vae-ft-mse does not appear to have a file named config.json.

### ISSUE THREAD

**Issue by nocynic** [smthemex/ComfyUI_EchoMimic#35]
<img width="706" alt="微信图片_20240727181512" src="https://github.com/user-attachments/assets/5559edfc-d0e9-4275-9b7d-9eba770299d1">

**Comment by nocynic** [comment]
搞定了

**Comment by m307160808** [comment]
> 搞定了

怎么弄的，请假一下，没看懂呢

**Comment by xiusidunhuren** [comment]
请问怎么搞定的
