### ISSUE TITLE
Return type mismatch between linked nodes: audio, AUDIO != STRING

### ISSUE THREAD

**Issue by jeffreyrobeson** [smthemex/ComfyUI_EchoMimic#36]
Prompt outputs failed validation
Echo_Sampler:
- Return type mismatch between linked nodes: audio, AUDIO != STRING
![085a33dc00d33b148645d639376cf07a](https://github.com/user-attachments/assets/be4eac21-be24-4052-a2b7-dce9dbd93cf7)

**Comment by smthemex** [comment]
请更新插件，最新的sampler节点多了一个功能，如果你用最新的工作流，会识别不到。
