### ISSUE TITLE
echo_loadmodel和echo sampler缺失，manager无法安装missing

### ISSUE THREAD

**Issue by aiwork11** [smthemex/ComfyUI_EchoMimic#44]
![微信截图_20240806044023](https://github.com/user-attachments/assets/3b3fc06f-2500-4a31-a6b4-759d269d6dec)

**Comment by aiwork11** [comment]
![微信截图_20240806044427](https://github.com/user-attachments/assets/bd51c544-c192-46b7-b36a-58ee412b741d)

**Comment by smthemex** [comment]
这个插件是无法用manager安装的，因为manager安装会让comfyUI现有的torch混乱，所以请务必按readme，便携包用python -m pip install 装好torch 三件套及opencv-python，xformers及ffmpeg 库，

**Comment by aiwork11** [comment]
感谢回复，我在python_embeded目录下安装好了opencv-python和xformers和torch 三件套，操作pip uninstall ffmpeg时说没有可以卸载的，输入pip install ffmpeg-python时又提示已安装。我用manager把echomimic卸载了，然后下载的安装包放到custum-nodes里。opencv-python在C盘安装过了。我安装的python是3.10，torch是2.2.0，torch-2.2.0+cu121-cp310-cp310-win_amd64，OpenCV是4.10.0.84。现在运行comfyUI,显示import failed，我真的不知道哪里的问题了，不懂编程的人被狠狠地虐了3天了。
![微信截图_20240807110959](https://github.com/user-attachments/assets/9ed0438d-4f39-4cb4-b1b2-73b0b4e32634)
![微信截图_20240807114244](https://github.com/user-attachments/assets/2b496c36-1055-46bc-9dbd-c266bce05c89)

**Comment by aiwork11** [comment]
我看到您在别人那里回复了关于FFMPEG的内容，试着输入pip install facenet_pytorch ffmpeg-python moviepy av，然后模型出来了。当然运行了之后，还是提示有问题，我再看看别人的提问。

**Comment by aiwork11** [comment]
@smthemex  一开始出错是我只下了acc版的models，但是在infer_mode那里没有改过来。后面有出了错误，提示的dict，我就搞不清楚是什么问题了，麻烦看一下，谢谢！
![微信截图_20240807123832](https://github.com/user-attachments/assets/51efbd56-ad6d-4f7c-bea8-98cab5904fb6)

**Comment by smthemex** [comment]
你这是VH的问题，可以更新一下VH

**Comment by aiwork11** [comment]
@smthemex 谢谢，可以走完流程了！

**Comment by jppqbg** [comment]
也是这个问题

**Comment by jppqbg** [comment]
python_embeded 没有这个文件夹@aiwork11

**Comment by jppqbg** [comment]
> 你这是VH的问题，可以更新一下VH

啥是VH啊

**Comment by smthemex** [comment]
> > 你这是VH的问题，可以更新一下VH
> 
> 啥是VH啊

ComfyUI-VideoHelperSuite  这个插件的问题，不是echo这个插件
