### ISSUE TITLE
关于图片尺寸问题。

### ISSUE THREAD

**Issue by JimWang151** [smthemex/ComfyUI_EchoMimic#47]
Hello,smthemex:

感谢您的辛苦。这个插件很好，多谢。

我看到在Sampler中，有关于width和height的设置（其中预设是512*512），想请教的是：

如果提供的图片长方形的，怎么样确保输出的图片不被裁剪呢？

**Comment by smthemex** [comment]
是中心裁切，根据W H值来裁切的，你把WH值设置为你的长方形的比例，比如长方形是4:3，那么尺寸设置为512/384就能避免裁切

**Comment by JimWang151** [comment]
> 是中心裁切，根据W H值来裁切的，你把WH值设置为你的长方形的比例，比如长方形是4:3，那么尺寸设置为512/384就能避免裁切

2：1是否可以？比如我设定：256/192？

**Comment by smthemex** [comment]
可以啊，但是最大数最好是512，小了质量不好

**Comment by JimWang151** [comment]
> 可以啊，但是最大数最好是512，小了质量不好

我试出来了，的确是512效果最好。回复很及时，非常感谢。

另外想请教，是否可以增加一个参数，让画面整体的运动幅度大一些或者小一些？

**Comment by smthemex** [comment]
大幅度的 要用参考视频的模式，选择幅度大的参考视频

**Comment by JimWang151** [comment]
> 大幅度的 要用参考视频的模式，选择幅度大的参考视频

**Can i have you wechat id? Mine:105833330.**

这个贴子可以结案了。

**Comment by XingML** [comment]
> 是中心裁切，根据W H值来裁切的，你把WH值设置为你的长方形的比例，比如长方形是4:3，那么尺寸设置为512/384就能避免裁切

您好，我试过把 wh设置为原画面的比例，但是生成的视频还是裁剪出来了脸部正方形区域，然后尺寸缩放到我设置的比例，导致脸部变形。 这个问题有解吗？

**Comment by smthemex** [comment]
说一下具体的裁切参数，我回头测试一下，这个项目很久没有更新了

**Comment by XingML** [comment]
> 说一下具体的裁切参数，我回头测试一下，这个项目很久没有更新了
输入图片尺寸 w*h=500*704，Echo_sampler中w和h 分别为384和512，其余为默认尺寸。 感谢！

**Comment by smthemex** [comment]
不过要晚几天，因为国庆前事比较多
