### ISSUE TITLE
How can I stitch the generation back to the whole image. Is there also a way to reduce the motion made in the generations?

### ISSUE THREAD

**Issue by nux1111** [smthemex/ComfyUI_EchoMimic#52]
How can I stitch the generation back to the whole image. Is there also a way to reduce the motion made in the generations?

**Comment by smthemex** [comment]
You can try using a full body video as a driving reference, and of course, you can also control the cropping factor
可以试着用全身的视频作为驱动参考，当然，也可以控制裁切系数

**Comment by nux1111** [comment]
Thanks
