### ISSUE TITLE
崩溃在采样器节点了。人也崩溃了。折腾了两周也反复看啦issuses，求救！

### ISSUE THREAD

**Issue by laochendeai** [smthemex/ComfyUI_EchoMimic#53]
![image](https://github.com/user-attachments/assets/6b1d5a53-9e78-4780-a79f-a3d463f067a3)

got prompt
D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\configuration_utils.py:245: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a model, please use <class 'ComfyUI_EchoMimic.src.models.unet_2d_condition.UNet2DConditionModel'>.load_config(...) followed by <class 'ComfyUI_EchoMimic.src.models.unet_2d_condition.UNet2DConditionModel'>.from_config(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  deprecate("config-passed-as-path", "1.0.0", deprecation_message, standard_warn=False)

D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\models\lora.py:306: FutureWarning: `LoRACompatibleConv` is deprecated and will be removed in version 1.0.0. Use of `LoRACompatibleConv` is deprecated. Please switch to PEFT backend by installing PEFT: `pip install peft`.
  deprecate("LoRACompatibleConv", "1.0.0", deprecation_message)

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py:514: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  reference_unet.load_state_dict(torch.load(re_ckpt, map_location="cpu"),strict=False)

loaded temporal unet's pretrained weights from D:\ComfyUI_windows_portable\ComfyUI\models\echo_mimic\unet ...
Load motion module params from D:\ComfyUI_windows_portable\ComfyUI\models\echo_mimic\motion_module.pth
Loaded 453.20928M-parameter motion module
D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py:549: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  denoising_unet.load_state_dict(torch.load(denois_pt, map_location="cpu"), strict=False)

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py:563: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  face_locator.load_state_dict(torch.load(face_locator_pt),strict=False)

D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\__init__.py:109: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fp, map_location=device)

D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\facenet_pytorch\models\mtcnn.py:34: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(state_dict_path)

D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\facenet_pytorch\models\mtcnn.py:79: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(state_dict_path)

D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\facenet_pytorch\models\mtcnn.py:132: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(state_dict_path)

!!! Exception during processing !!! [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 678, in em_main
    output_video,audio_form_v= process_video(image, audio_file, width, height, length, seeds, facemask_ratio,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\EchoMimic_node.py", line 208, in process_video
    video = pipe(
            ^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\pipelines\pipeline_echo_mimic.py", line 394, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_EchoMimic\src\models\whisper\whisper\audio.py", line 44, in load_audio
    .run(cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
              ^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1538, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by laochendeai** [comment]
已解决，按照博主这个连接https://github.com/smthemex/ComfyUI_EchoMimic/issues/16#issuecomment-2242807874

**Comment by laochendeai** [comment]
> 已解决，按照博主这个连接[#16 (comment)](https://github.com/smthemex/ComfyUI_EchoMimic/issues/16#issuecomment-2242807874)

先进D:\ComfyUI_windows_portable\python_embeded\输入cmd，在命令行执行
python -m pip uninstall torchaudio torchvision torch xformers ffmpeg
下载预编译ffmpeg版本，放在便携式comfyui的目录下，把D:\ComfyUI_windows_portable\ComfyUI\ffmpeg\bin这个目录加入**系统环境变量**的路径中，再把D:\ComfyUI_windows_portable\python_embeded\Scripts这个目录同样加入**系统环境变量**的路径中，关闭所有命令行窗口。
再进D:\ComfyUI_windows_portable\python_embeded\输入cmd，在命令行执行
python -m pip install torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121
python -m pip install xformers==0.0.24
python -m pip install facenet_pytorch ffmpeg-python moviepy av

**Comment by s130166** [comment]
@ smthemex 请问大佬，我也按照页面，到了加载出现错误。请教一下怎么处理，
![微信截图_20241120161905](https://github.com/user-attachments/assets/efd1ef29-89c0-4ffe-a259-e28421bb63ad)


Prompt executed in 0.06 seconds
got prompt
when facecrop_ratio=1.0,The maximum image size will be obtained, but there may be edge deformation.** 选择最大裁切为1.0时，边缘可能会出现形变！
**** Use  audio drive video! ****
!!! Exception during processing !!! [WinError 2] 系统找不到指定的文件。
Traceback (most recent call last):
  File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\EchoMimic_node.py", line 357, in em_main
    output_video= process_video(image, audio_file, width, height, length, seeds, facemask_ratio,
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\utils.py", line 118, in process_video
    video = pipe(
  File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\pipelines\pipeline_echo_mimic_acc.py", line 396, in __call__
    whisper_feature = self.audio_guider.audio2feat(audio_path)
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\audio2feature.py", line 100, in audio2feat
    result = self.model.transcribe(audio_path)
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\whisper\transcribe.py", line 85, in transcribe
    mel = log_mel_spectrogram(audio)
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
  File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\whisper\audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
  File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1720, in runner
  File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 224, in sentry_patched_popen_init
  File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

Prompt executed in 0.24 seconds

**Comment by laochendeai** [comment]
您的来信已经收到，我会尽快给您回复。

**Comment by smthemex** [comment]
> @ smthemex 请问大佬，我也按照页面，到了加载出现错误。请教一下怎么处理， ![微信截图_20241120161905](https://private-user-images.githubusercontent.com/173974134/388005055-efd1ef29-89c0-4ffe-a259-e28421bb63ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTQ3NTgsIm5iZiI6MTczMjA5NDQ1OCwicGF0aCI6Ii8xNzM5NzQxMzQvMzg4MDA1MDU1LWVmZDFlZjI5LTg5YzAtNGZmZS1hMjU5LWUyODQyMWJiNjNhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwOTIwNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZTI3MDUyNGRmMzAzMjcwNDcxN2EwMDRiZGQ2NTc3ZWM4NjllYmYyM2Y0MTFmNzAxYTFhZTk1MDNiNWU4Njk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.31O-Hi-vw15MbezSYpU68J6pFXVI7l-MA0rcp9Fefdk)
> 
> Prompt executed in 0.06 seconds got prompt when facecrop_ratio=1.0,The maximum image size will be obtained, but there may be edge deformation.** 选择最大裁切为1.0时，边缘可能会出现形变！ **** Use audio drive video! **** !!! Exception during processing !!! [WinError 2] 系统找不到指定的文件。 Traceback (most recent call last): File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "D:\SD\SD\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\EchoMimic_node.py", line 357, in em_main output_video= process_video(image, audio_file, width, height, length, seeds, facemask_ratio, File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\utils.py", line 118, in process_video video = pipe( File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\pipelines\pipeline_echo_mimic_acc.py", line 396, in **call** whisper_feature = self.audio_guider.audio2feat(audio_path) File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\audio2feature.py", line 100, in audio2feat result = self.model.transcribe(audio_path) File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\whisper\transcribe.py", line 85, in transcribe mel = log_mel_spectrogram(audio) File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\whisper\audio.py", line 111, in log_mel_spectrogram audio = load_audio(audio) File "D:\SD\SD\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_EchoMimic-main\src\models\whisper\whisper\audio.py", line 42, in load_audio ffmpeg.input(file, threads=0) File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ffmpeg_run.py", line 313, in run process = run_async( File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\site-packages\ffmpeg_run.py", line 284, in run_async return subprocess.Popen( File "<enhanced_experience vendors.sentry_sdk.utils>", line 1720, in runner File "<enhanced_experience vendors.sentry_sdk.integrations.stdlib>", line 224, in sentry_patched_popen_init File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\subprocess.py", line 971, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "D:\SD\SD\ComfyUI-aki-v1.4\python\lib\subprocess.py", line 1456, in _execute_child hp, ht, pid, tid = _winapi.CreateProcess(executable, args, FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> 
> Prompt executed in 0.24 seconds

这是ffmpeg 错误，这个issues里有解决的办法，你仔细找找吧
你能进插件，说明你的facenet_pytorch安装好了 就安装以下
python -m pip install  ffmpeg-python moviepy av

**Comment by smthemex** [comment]
![image](https://github.com/user-attachments/assets/c3d845aa-5f4c-4bfd-9960-3cb04cb38d1a)
叉掉的去掉，你按这个步骤操作了没有？

**Comment by s130166** [comment]
> ![图像](https://private-user-images.githubusercontent.com/138738845/388086105-c3d845aa-5f4c-4bfd-9960-3cb04cb38d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDgxODUsIm5iZiI6MTczMjEwNzg4NSwicGF0aCI6Ii8xMzg3Mzg4NDUvMzg4MDg2MTA1LWMzZDg0NWFhLTVmNGMtNGJmZC05OTYwLTNjYjA0Y2IzOGQxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMzA0NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYzAwYjlmYzI0NjcxZGQ1MjY5NDFhMmY3ZWRhNjFiNzZhMjBkMWZjYmQ0NTQ5ZjEwZjdmZTgwZDVlNTdjYjM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.akyB5obzt_MzWrJ9Lb6UfqHpUVjBnY0ANWgSmyAw6ag)叉掉的去掉，你按这个步骤操作了没有？ 你这个主要是ffmpeg 的问题，你按我图示解决ffmpge的安装就好，其他的xformer什么的不用管

![11111](https://github.com/user-attachments/assets/8ec5d9b6-866c-4f3c-8c5c-65cb598bf459)
![44444](https://github.com/user-attachments/assets/a10935f3-af05-427c-b8d2-92a5cf739ae5)
![222222](https://github.com/user-attachments/assets/ffd753c5-685e-4048-92f5-0982d7441168)
![333333](https://github.com/user-attachments/assets/c7aceb21-037a-4aff-9db4-5fa96a2543a4)

**Comment by s130166** [comment]
> ![图像](https://private-user-images.githubusercontent.com/138738845/388086105-c3d845aa-5f4c-4bfd-9960-3cb04cb38d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMDk4NTIsIm5iZiI6MTczMjEwOTU1MiwicGF0aCI6Ii8xMzg3Mzg4NDUvMzg4MDg2MTA1LWMzZDg0NWFhLTVmNGMtNGJmZC05OTYwLTNjYjA0Y2IzOGQxYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQxMzMyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDE0ZjJiZTliNDIwZThhMzg1YjZjZGRjMjA0NzA2YTFiOTk5MTg1ZDRkZWQyNDIzM2M4ZDkwM2NmYzAwMmViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Xa0P1cUcZwp9On_ooJVw0RdTlF9A9Qc82dnOcH-hMlI)叉掉的去掉，你按这个步骤操作了没有？ 你这个主要是ffmpeg 的问题，你按我图示解决ffmpge的安装就好，其他的xformer什么的不用管

大佬，我重启了，好像可以用了，谢谢你解答
![image](https://github.com/user-attachments/assets/69bf1a09-4789-4ba5-ba38-7ad06491b95f)

**Comment by smthemex** [comment]
你的是让人头大的秋叶包，本来应该是\python\scripts 和 \python 加入系统变量，但是你是用的conda，可能秋叶的沙箱也能调用

**Comment by s130166** [comment]
> 你的是让人头大的秋叶包，本来应该是\python\scripts 和 \python 加入系统变量，但是你是用的conda，可能秋叶的沙箱也能调用

我也不懂，我看上面那个conda，我AI搜索安装的，我对编程一窍不通。误打误撞

**Comment by smthemex** [comment]
你应该在秋叶的控制台里直接安装就好，不过能用就行，这个话题结束了。
