### ISSUE TITLE
系统找不到指定文件

### ISSUE THREAD

**Issue by zxy1213upup** [smthemex/ComfyUI_EchoMimic#55]
你好，所依赖的版本应该如何控制
![756b7c5a-109c-4b21-b44f-4142441faad3](https://github.com/user-attachments/assets/df20befe-6517-4638-b7f2-b02a224405a6)

![ece22ab3-f088-407c-b231-02f38d520812](https://github.com/user-attachments/assets/31144ab8-c05c-4def-9713-4cc451bc016e)

**Comment by smthemex** [comment]
看第一张图是ffmpeg的问题，跟其他依赖没关系
