### ISSUE TITLE
Best practices around opencv-python and torch 

### ISSUE THREAD

**Issue by DhruvMalhotra** [smthemex/ComfyUI_EchoMimic#60]
Thanks for creating this, excited to try it out for an educational app we are making.

Could you elaborate on this text
"The highest supported version of OpenCV Python is Torch 2.2.0. If your Torch version is higher, during the first installation, you can use -- no deps Torch to ignore the installation of Torch, or install it directly, then delete Torch and install a higher version of Torch, If it is a portable package, you need to run python - m pip install XXX or python - m pip uninstall XXX in the python-embedded directory. Here is an example: torch2.4"

Do we want to end up with a torch version above 2.2.0 or not.

`pip install opencv-python`

This doesn't lead to a torch version being installed, so why the instruction around uninstalling torch after it?

Appreciate the clarity and thanks again for making this available to the community :)

**Comment by smthemex** [comment]
If OpenCV Python is installed for the first time and -- no deps is specified, during the installation process, Torch 2.2.0 will be automatically installed and uninstalled from this higher version of Torch. However, this can cause an unavoidable error in ComfyUI, as Torch 2.2.0 automatically installed by OpenCV Python is not a CUDA version.
So, if you don't use -- no deps, my recommended installation method is to first successfully install OpenCV Python, then uninstall Torch, and then install Torch with CUDA (after testing, it has been found that after successfully installing OpenCV Python, higher versions of Torch are also compatible).
Of course, if your OpenCV Python is already the highest version and Torch is running properly, there is no need to install it

**Comment by DhruvMalhotra** [comment]
Much clearer now thanks!
I ended up doing that and for those viewing this, I also had the additional problem that on Windows 10 I did not have the "Windows Media feature pack" installed. Installing it fixed `import cv2`.
Instructions here: https://stackoverflow.com/questions/77440408/how-should-i-handle-a-windows-media-feature-pack-dependency-from-an-installer
