### ISSUE TITLE
pip install xformers==0.0.26  

### ISSUE THREAD

**Issue by DhruvMalhotra** [smthemex/ComfyUI_EchoMimic#61]
This version of formers is not available anymore and throws

`ERROR: Could not find a version that satisfies the requirement xformers==0.0.26 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.20, 0.0.21, 0.0.22, 0.0.22.post7, 0.0.23, 0.0.23.post1, 0.0.24, 0.0.25, 0.0.25.post1, 0.0.26.post1, 0.0.27, 0.0.27.post1, 0.0.27.post2, 0.0.28, 0.0.28.post1, 0.0.29.dev921, 0.0.29.dev922)
ERROR: No matching distribution found for xformers==0.0.26`

Moving to 0.0.26.post1 upgrades torch 2.2 -> 2.3 and then throws

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.2.0+cu121 requires torch==2.2.0+cu121, but you have torch 2.3.0 which is incompatible.
ch 2.3.0 which is incompatible.`

Appreciate the help!

**Comment by smthemex** [comment]
pip install xformers==0.0.26.post1 
the issue 2，first：
pip uninstall torchaudio torchvision torch xformers 
then：
pip install torch==2.3.0 torchvision==0.18.0 torchaudio==2.3.0 --index-url https://download.pytorch.org/whl/cu121
pip install xformers==0.0.26.post1
