### ISSUE TITLE
Error in Echo Load Model node

### ISSUE THREAD

**Issue by myprivacygithub** [smthemex/ComfyUI_EchoMimic#63]
PytorchStreamReader failed reading file data/294: invalid header or archive is corrupted

![Screenshot (616)](https://github.com/user-attachments/assets/20ea2e48-b247-4898-a560-7a28d1af8bd9)

**Comment by smthemex** [comment]
make sure your checkpoints is in folder

**Comment by myprivacygithub** [comment]
my mistake, its working now.
