### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by sugatasanshiro** [smthemex/ComfyUI_EchoMimic#67]
![brave_XaQRWgPTkM](https://github.com/user-attachments/assets/31e46220-fcf6-4e67-87ff-a4cd3d0980bc)

![cmd_VrUupEj9Ft](https://github.com/user-attachments/assets/23cf49e6-5514-412a-9466-4b7ad44bfef3)

**Comment by smthemex** [comment]
You using a webUI, it 's not  my work,
