### ISSUE TITLE
是否支持1920*1080分辨率的视频，该如何配置？

### ISSUE THREAD

**Issue by fullstackpeng** [smthemex/ComfyUI_EchoMimic#74]
![image](https://github.com/user-attachments/assets/01f446b1-062f-4ffc-8323-78814fea1e75)
如题，显卡为4090 24G显存

**Comment by smthemex** [comment]
1920这个尺寸4090也不一定跑得动，然后模型是基于512*512的训练集训练的，大了效果我有不知道会怎么样

**Comment by fullstackpeng** [comment]
好吧😥
