### ISSUE TITLE
v1版本，参考了源代码的配置，感觉生成出来的还是比较僵硬

### ISSUE THREAD

**Issue by GoToBoy** [smthemex/ComfyUI_EchoMimic#85]
![image](https://github.com/user-attachments/assets/8d12b458-e9a4-4b5e-bceb-453ac9ae3bb2)
![image](https://github.com/user-attachments/assets/0f7db801-17d3-4135-87b1-c0e3942ae359)

大神， 请问是哪里参数配置有问题？

**Comment by GoToBoy** [comment]
![20241126092302_rec_](https://github.com/user-attachments/assets/1ce77923-417f-4aca-b58d-0040a51ffe0e)

**Comment by smthemex** [comment]
把降噪打开
