### ISSUE TITLE
如何更换其他的POS动作？哪里可以下载替换哪里，还有就是v2可以用可选择V1模型就报错

### ISSUE THREAD

**Issue by rong7932** [smthemex/ComfyUI_EchoMimic#89]
官方好些个动作，这个目前只有一个固定的动作动画，能改？哪里下载替换？

**Comment by smthemex** [comment]
官方的代码还没有更新，他们还在做对齐工作，既有的官方公开的代码是缺失了模型对齐的部分的，虽然目前也有其他开发者做了对齐项目，但是我还是想等官方的代码吧再植入吧。

**Comment by rong7932** [comment]
> 官方的代码还没有更新，他们还在做对齐工作，既有的官方公开的代码是缺失了模型对齐的部分的，虽然目前也有其他开发者做了对齐项目，但是我还是想等官方的代码吧再植入吧。

好的知道了谢谢，还有就是由于无法改变动作，所以我想用V1版本想只做个头部的，可选择V1的时候报错这个
![微信图片_20241126214252](https://github.com/user-attachments/assets/a4afe778-3043-4115-9a9d-88e56b41ff12)

![微信图片_20241126214252](https://github.com/user-attachments/assets/656fd862-b7ca-489e-af41-f2eda63f7511)
不知道如何解决，V2正常生成

**Comment by smthemex** [comment]
V1版本要安装 facenet_pytorch才行，这个库安装比较繁琐，你自己看issue 和我的说明文档吧

**Comment by rong7932** [comment]
> V1版本要安装 facenet_pytorch才行，这个库安装比较繁琐，你自己看issue 和我的说明文档吧

好的，还是等V2多动作更新吧 谢谢，所有下载的模型都在 echo_mimic 这里吧，点V1下了一堆模型还用不了 我得给清理了
