### ISSUE TITLE
我用50秒的音频驱动，length也设置成2000了，为什么只能生成13秒的视频

### ISSUE THREAD

**Issue by helloworlda756** [smthemex/ComfyUI_EchoMimic#94]
我用50秒的音频驱动，length也设置成2000了，为什么只能生成13秒的视频

**Comment by smthemex** [comment]
纯音频驱动实际输出长度是以“音频时长，length/fps” 来取二者最小值的，
如果是视频驱动或者V2版本，实际输出时长是“音频时长，length/fps，V2的npy蒙版数量(或者V1的pkl数量)除以fps”三者的最小值 。
你生成13秒，多半是用的V2版本，也就是336/25 大约13秒，没什么问题。
V2版本的自定义视频驱动，还要等一下官方的代码更新，如果他们不更新，我再考虑自己写非官方的重构。
还有麻烦不要发2个一样的issues，这里不是贴吧，1个issues就给我爆一个邮件，很麻烦的。

**Comment by lejun82** [comment]
infer length is 336
这个上限如何自定义可以修改下？

**Comment by smthemex** [comment]
上限是npy的蒙版文件数量限制，你复制10份，然后从0开始重命名，就有3360的长度了。

**Comment by lejun82** [comment]
超过380就torch.OutOfMemoryError.....还是等优化版本吧，希望能尽快出来 : )
