### ISSUE TITLE
fps降低会导致默认pose变成慢动作

### ISSUE THREAD

**Issue by qy8502** [smthemex/ComfyUI_EchoMimic#97]
为了配合ppt演示，弄个12fps的视频凑合一下，但是动作变慢，什么参数可以解决这个问题？

**Comment by smthemex** [comment]
pose的npy文件 复制一份或者多份，然后全部重命名，注意命名的方式，文件所在[地址](https://github.com/smthemex/ComfyUI_EchoMimic/tree/main/echomimic_v2/assets/halfbody_demo/pose/01)

**Comment by qy8502** [comment]
> pose的npy文件 复制一份或者多份，然后全部重命名，注意命名的方式，文件所在[地址](https://github.com/smthemex/ComfyUI_EchoMimic/tree/main/echomimic_v2/assets/halfbody_demo/pose/01)

哦，你解答了我为什么视频最多只有14秒的问题，因为24帧下，pose只够14秒的。复制多份可以延长视频时长，那么中间删除一些帧的pose可以解决慢动作的问题了，谢谢！
